name: chat_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.16.1
  dash_chat_2: ^0.0.20
  delightful_toast: ^1.1.0
  firebase_analytics: ^10.10.1
  firebase_auth: ^4.19.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.7.1
  flutter:
    sdk: flutter
  get_it: ^7.6.8
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  navigation_utils: ^0.5.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
